=== Dr-JohnWalls/Learn-Power-Query/Chapter07/Import/RESULTS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="RESULTS" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="RESULTS">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Code" index-key="Code " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="SubjCode" index-key="SubjCode " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="p95fgUTIM0OuTX48I6uO8Q==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACn3l+BRMgzQ65Nfjwjq47xAAAAAFo5PwbbauVAAAAAAAAAAABSAEUA
UwBVAEwAVABTAAAAAAAAAFDQETqxi3xBkDhlGnEaUTsHAAAAp95fgUTIM0OuTX48
I6uO8UMAbwBkAGUAAAAAAAAAX6EPdk0GbUa0otpbExvmsAcAAACn3l+BRMgzQ65N
fjwjq47xUwB1AGIAagBDAG8AZABlAAAAAAAAAL8bCbfZHfFClfrXuLSuIesHAAAA
p95fgUTIM0OuTX48I6uO8U0AYQByAGsAAAAAAAAAI6XKeibZ6kWXkEjjsiy82wcA
AACn3l+BRMgzQ65Nfjwjq47xVABlAHIAbQAAAAAAAAAR2dgZMKObQqjEb9g154mH
BwAAAKfeX4FEyDNDrk1+PCOrjvFDAG8AbQBtAGUAbgB0AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAMAAAABQAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Code" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="UNAROrGLfEGQOGUacRpROw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SubjCode" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="X6EPdk0GbUa0otpbExvmsA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Mark" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="vxsJt9kd8UKV+te4tK4h6w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Term" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="I6XKeibZ6kWXkEjjsiy82w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Comment" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="EdnYGTCjm0KoxG/YNeeJhw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Dr-JohnWalls/Learn-Power-Query/Chapter07/Import/RESULTS.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="RESULTS.xsd" generated="2020-05-17T12:47:19">
<RESULTS>
<Code>1341</Code>
<SubjCode>2</SubjCode>
<Mark>78</Mark>
<Term>3</Term>
</RESULTS>
<RESULTS>
<Code>1341</Code>
<SubjCode>3</SubjCode>
<Mark>34</Mark>
<Term>3</Term>
</RESULTS>
<RESULTS>
<Code>429</Code>
<SubjCode>4</SubjCode>
<Mark>55</Mark>
<Term>2</Term>
</RESULTS>
<RESULTS>
<Code>881</Code>
<SubjCode>5</SubjCode>
<Mark>80</Mark>
<Term>3</Term>
</RESULTS>
<RESULTS>
<Code>881</Code>
<SubjCode>6</SubjCode>
<Mark>55</Mark>
<Term>3</Term>
</RESULTS>
<RESULTS>
<Code>881</Code>
<SubjCode>7</SubjCode>
<Mark>92</Mark>
<Term>3</Term>
</RESULTS>
<RESULTS>
<Code>881</Code>
<SubjCode>8</SubjCode>
<Mark>43</Mark>
<Term>2</Term>
</RESULTS>
<RESULTS>
<Code>82</Code>
<SubjCode>9</SubjCode>
<Mark>23</Mark>
<Term>2</Term>
</RESULTS>
<RESULTS>
<Code>82</Code>
<SubjCode>10</SubjCode>
<Mark>55</Mark>
<Term>2</Term>
</RESULTS>
<RESULTS>
<Code>82</Code>
<SubjCode>11</SubjCode>
<Mark>98</Mark>
<Term>3</Term>
</RESULTS>
<RESULTS>
<Code>82</Code>
<SubjCode>12</SubjCode>
<Mark>45</Mark>
<Term>3</Term>
</RESULTS>
<RESULTS>
<Code>82</Code>
<SubjCode>13</SubjCode>
<Mark>67</Mark>
<Term>2</Term>
</RESULTS>
<RESULTS>
<Code>412</Code>
<SubjCode>14</SubjCode>
<Mark>65</Mark>
<Term>2</Term>
</RESULTS>
<RESULTS>
<Code>412</Code>
<SubjCode>15</SubjCode>
<Mark>44</Mark>
<Term>3</Term>
</RESULTS>
<RESULTS>
<Code>412</Code>
<SubjCode>16</SubjCode>
<Mark>76</Mark>
<Term>3</Term>
</RESULTS>
<RESULTS>
<Code>412</Code>
<SubjCode>17</SubjCode>
<Mark>54</Mark>
<Term>3</Term>
</RESULTS>
</dataroot>
